venturenative-app:
    build: .
    dockerfile: Dockerfile
    environment:
        - NODE_ENV=production
    volumes:
        - .:/app
        - /app/node_modules
    ports:
        - '5000:5000'
    restart: on-failure
